Apriori Algorithmn

In [9]:
from collections import defaultdict

def min_supp_count(min_supp, total_trans):
    count = min_supp * total_trans  # min_supp is percentage (e.g., 0.05 for 5%)
    return count

def get_frequent_itemsets(data, min_supp_count_value):

    symptom_counts = defaultdict(int)

    for i in data: #loop throgh the list and count
        for j in i:
            symptom_counts[j] += 1

    # Filter by minimum support
    frequent = {}
    for i in symptom_counts:
        count = symptom_counts[i]
        if count >= min_supp_count_value:
            frequent[frozenset([i])] = count


    list_for_rule_generation = frequent.copy() #make a copy to store all frequent items
    templist = frequent
    k = 2

    print(f"Found {len(frequent)} frequent 1 itemsets")

    #Generate larger itemsets
    while templist:
        print(f"Generating {k} itemsets")

        # Create candidate itemsets
        candidates = set()
        itemsets_list = list(templist.keys())

        # Combine itemsets
        for i in range(len(itemsets_list)):
            for j in range(i + 1, len(itemsets_list)):
                itemset1 = itemsets_list[i]
                itemset2 = itemsets_list[j]

                # Check if 2 itemsets have something in common then fuse them
                union_set = itemset1.union(itemset2)
                if len(union_set) == k:
                    candidates.add(union_set)

        if not candidates: #if nothing to combine then exits
            break

        # Count support
        candidate_support = {}
        for candidate in candidates:
            count = 0
            for transaction in data:
                if candidate.issubset(set(transaction)):
                    count += 1

            if count >= min_supp_count_value:
                candidate_support[candidate] = count

        if not candidate_support:
            break

        print(f"Found {len(candidate_support)} frequent {k}-itemsets")
        list_for_rule_generation.update(candidate_support)
        templist = candidate_support
        k += 1

    return list_for_rule_generation

def generate_association_rules(frequent_itemsets, min_confidence, total_transactions):

    rules = []

    for itemset, support_count in frequent_itemsets.items():
        if len(itemset) >= 2:  # generate rules for itemsets with at least 2 items
            items_list = list(itemset)

            # Generate all possible rules for this itemset
            # For itemset {A,B,C}, generate rules eg a-bc, b-ac ....
            from itertools import combinations

            # Generate all non-empty proper subsets on the left
            for r in range(1, len(items_list)):
                for antecedent_items in combinations(items_list, r):
                    antecedent_set = frozenset(antecedent_items)
                    consequent_set = itemset - antecedent_set

                    # Calculate confidence
                    if antecedent_set in frequent_itemsets:
                        antecedent_support = frequent_itemsets[antecedent_set] #(total set count)/(left set count)
                        confidence = support_count / antecedent_support

                        if confidence >= min_confidence: #add into rules if it is >= to the minconfidence
                            rules.append({
                                'rule_id': len(rules) + 1,
                                'antecedent': antecedent_set, #left
                                'consequent': consequent_set, #right
                                'support': support_count / total_transactions,
                                'support_count': support_count,
                                'confidence': confidence
                            })

    return rules

def apriori2(data, min_supp, confidence):

    total_count = len(data)
    min_supp_count_value = min_supp_count(min_supp, total_count)

    print(f"Apriori")
    print(f"Total transactions: {total_count}")
    print(f"Minimum support: {min_supp:.1%} (≥{min_supp_count_value})")
    print(f"Minimum confidence: {confidence:.1%}")

    frequent_itemsets = get_frequent_itemsets(data, min_supp_count_value)

    itemset_sizes = {}
    for itemset in frequent_itemsets.keys():
        size = len(itemset)
        itemset_sizes[size] = itemset_sizes.get(size, 0) + 1

    for size, count in sorted(itemset_sizes.items()):
        print(f"  {size}-itemsets: {count}")

    print(f"\nSTEP 2: GENERATING ASSOCIATION RULES...")
    rules = generate_association_rules(frequent_itemsets, confidence, total_count)

    print(f"Generated {len(rules)} association rules")

    return frequent_itemsets, rules

Import Dataset

In [10]:
import os
import pandas as pd

import pandas as pd
import os

# Load the dataset.csv file
df = pd.read_csv(r'C:\Users\rqpua\Downloads\dataset.csv')
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
## Data Cleaning step

df.fillna(0,inplace=True)

In [13]:
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Fungal infection,itching,skin_rash,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [14]:
#See all the symptoms
symptom_columns = [col for col in df.columns if col.startswith('Symptom_')]

#Get unique ones
all_symptoms = df[symptom_columns].values.flatten()
unique_symptoms = pd.unique(all_symptoms)

# Remove any NaN values
unique_symptoms = unique_symptoms[~pd.isna(unique_symptoms)]

print(f"Found {len(unique_symptoms)} unique symptoms:")
print(unique_symptoms)

Found 132 unique symptoms:
['itching' ' skin_rash' ' nodal_skin_eruptions' ' dischromic _patches' 0
 ' continuous_sneezing' ' shivering' ' chills' ' watering_from_eyes'
 ' stomach_pain' ' acidity' ' ulcers_on_tongue' ' vomiting' ' cough'
 ' chest_pain' ' yellowish_skin' ' nausea' ' loss_of_appetite'
 ' abdominal_pain' ' yellowing_of_eyes' ' burning_micturition'
 ' spotting_ urination' ' passage_of_gases' ' internal_itching'
 ' indigestion' ' muscle_wasting' ' patches_in_throat' ' high_fever'
 ' extra_marital_contacts' ' fatigue' ' weight_loss' ' restlessness'
 ' lethargy' ' irregular_sugar_level' ' blurred_and_distorted_vision'
 ' obesity' ' excessive_hunger' ' increased_appetite' ' polyuria'
 ' sunken_eyes' ' dehydration' ' diarrhoea' ' breathlessness'
 ' family_history' ' mucoid_sputum' ' headache' ' dizziness'
 ' loss_of_balance' ' lack_of_concentration' ' stiff_neck' ' depression'
 ' irritability' ' visual_disturbances' ' back_pain' ' weakness_in_limbs'
 ' neck_pain' ' weakness_of_one_body_side' ' altered_sensorium'
 ' dark_urine' ' sweating' ' muscle_pain' ' mild_fever'
 ' swelled_lymph_nodes' ' malaise' ' red_spots_over_body' ' joint_pain'
 ' pain_behind_the_eyes' ' constipation' ' toxic_look_(typhos)'
 ' belly_pain' ' yellow_urine' ' receiving_blood_transfusion'
 ' receiving_unsterile_injections' ' coma' ' stomach_bleeding'
 ' acute_liver_failure' ' swelling_of_stomach' ' distention_of_abdomen'
 ' history_of_alcohol_consumption' ' fluid_overload' ' phlegm'
 ' blood_in_sputum' ' throat_irritation' ' redness_of_eyes'
 ' sinus_pressure' ' runny_nose' ' congestion' ' loss_of_smell'
 ' fast_heart_rate' ' rusty_sputum' ' pain_during_bowel_movements'
 ' pain_in_anal_region' ' bloody_stool' ' irritation_in_anus' ' cramps'
 ' bruising' ' swollen_legs' ' swollen_blood_vessels'
 ' prominent_veins_on_calf' ' weight_gain' ' cold_hands_and_feets'
 ' mood_swings' ' puffy_face_and_eyes' ' enlarged_thyroid'
 ' brittle_nails' ' swollen_extremeties' ' abnormal_menstruation'
 ' muscle_weakness' ' anxiety' ' slurred_speech' ' palpitations'
 ' drying_and_tingling_lips' ' knee_pain' ' hip_joint_pain'
 ' swelling_joints' ' painful_walking' ' movement_stiffness'
 ' spinning_movements' ' unsteadiness' ' pus_filled_pimples' ' blackheads'
 ' scurring' ' bladder_discomfort' ' foul_smell_of urine'
 ' continuous_feel_of_urine' ' skin_peeling' ' silver_like_dusting'
 ' small_dents_in_nails' ' inflammatory_nails' ' blister'
 ' red_sore_around_nose' ' yellow_crust_ooze']

In [15]:
# Clean the data 
df_clean = df.copy()
symptom_cols = [col for col in df.columns if col.startswith('Symptom_')]

#Clean the symptom strings 
for col in symptom_cols:
    df_clean[col] = df_clean[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

#Apply standardization for names of similiar meaning
symptom_mapping = {
    'abdominal_pain': 'stomach_pain',
    'belly_pain': 'stomach_pain'
}

for col in symptom_cols:
    df_clean[col] = df_clean[col].replace(symptom_mapping)

#Get unique symptoms and clean them
all_symptoms_clean = df_clean[symptom_cols].values.flatten()
unique_symptoms_clean = pd.unique(all_symptoms_clean)

# Filter out NaN, 0, and empty values, then convert to strings
unique_symptoms_clean = [str(s).strip() for s in unique_symptoms_clean 
                        if not pd.isna(s) and s != 0 and s != '0' and str(s).strip() != '']

# Remove duplicates after cleaning
unique_symptoms_clean = list(set(unique_symptoms_clean))

print(f"After proper standardization: {len(unique_symptoms_clean)} unique symptoms")
print("Standardized symptoms:")
for symptom in sorted(unique_symptoms_clean):
    print(f"- {symptom}")

After proper standardization: 129 unique symptoms
Standardized symptoms:
- abnormal_menstruation
- acidity
- acute_liver_failure
- altered_sensorium
- anxiety
- back_pain
- blackheads
- bladder_discomfort
- blister
- blood_in_sputum
- bloody_stool
- blurred_and_distorted_vision
- breathlessness
- brittle_nails
- bruising
- burning_micturition
- chest_pain
- chills
- cold_hands_and_feets
- coma
- congestion
- constipation
- continuous_feel_of_urine
- continuous_sneezing
- cough
- cramps
- dark_urine
- dehydration
- depression
- diarrhoea
- dischromic _patches
- distention_of_abdomen
- dizziness
- drying_and_tingling_lips
- enlarged_thyroid
- excessive_hunger
- extra_marital_contacts
- family_history
- fast_heart_rate
- fatigue
- fluid_overload
- foul_smell_of urine
- headache
- high_fever
- hip_joint_pain
- history_of_alcohol_consumption
- increased_appetite
- indigestion
- inflammatory_nails
- internal_itching
- irregular_sugar_level
- irritability
- irritation_in_anus
- itching
- joint_pain
- knee_pain
- lack_of_concentration
- lethargy
- loss_of_appetite
- loss_of_balance
- loss_of_smell
- malaise
- mild_fever
- mood_swings
- movement_stiffness
- mucoid_sputum
- muscle_pain
- muscle_wasting
- muscle_weakness
- nausea
- neck_pain
- nodal_skin_eruptions
- obesity
- pain_behind_the_eyes
- pain_during_bowel_movements
- pain_in_anal_region
- painful_walking
- palpitations
- passage_of_gases
- patches_in_throat
- phlegm
- polyuria
- prominent_veins_on_calf
- puffy_face_and_eyes
- pus_filled_pimples
- receiving_blood_transfusion
- receiving_unsterile_injections
- red_sore_around_nose
- red_spots_over_body
- redness_of_eyes
- restlessness
- runny_nose
- rusty_sputum
- scurring
- shivering
- silver_like_dusting
- sinus_pressure
- skin_peeling
- skin_rash
- slurred_speech
- small_dents_in_nails
- spinning_movements
- spotting_ urination
- stiff_neck
- stomach_bleeding
- stomach_pain
- sunken_eyes
- sweating
- swelled_lymph_nodes
- swelling_joints
- swelling_of_stomach
- swollen_blood_vessels
- swollen_extremeties
- swollen_legs
- throat_irritation
- toxic_look_(typhos)
- ulcers_on_tongue
- unsteadiness
- visual_disturbances
- vomiting
- watering_from_eyes
- weakness_in_limbs
- weakness_of_one_body_side
- weight_gain
- weight_loss
- yellow_crust_ooze
- yellow_urine
- yellowing_of_eyes
- yellowish_skin

In [16]:
df_clean.head(4920)

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Fungal infection,itching,skin_rash,dischromic _patches,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,0,0,0,0,0,0,0,0,0,0,0
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,0,0,0,0,0,0,0,0,0,0,0,0,0
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,0,0,0,0,0,0,0,0,0,0,0,0,0
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,0,0,0,0,0,0,0,0,0,0,0
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,0,0,0,0,0,0,0,0,0,0,0,0

In [17]:
# Make each row as a basket and remove disease 
symptom_cols = [col for col in df_clean.columns if col.startswith('Symptom_')]

transactions_clean = []
for i in range(len(df_clean)):
    transaction = []
    for col in symptom_cols:
        symptom_value = df_clean.loc[i, col]
        if str(symptom_value) != '0' and not pd.isna(symptom_value) and str(symptom_value).strip() != '':
            transaction.append(str(symptom_value).strip())
    transactions_clean.append(transaction)

print(f"Created {len(transactions_clean)} cleaned transactions")
print("First 5 cleaned transactions:")
for i in range(5):
    print(f"{df_clean.loc[i, 'Disease']}: {transactions_clean[i]}")

Created 4920 cleaned transactions
First 5 cleaned transactions:
Fungal infection: ['itching', 'skin_rash', 'nodal_skin_eruptions', 'dischromic _patches']
Fungal infection: ['skin_rash', 'nodal_skin_eruptions', 'dischromic _patches']
Fungal infection: ['itching', 'nodal_skin_eruptions', 'dischromic _patches']
Fungal infection: ['itching', 'skin_rash', 'dischromic _patches']
Fungal infection: ['itching', 'skin_rash', 'nodal_skin_eruptions']

In [18]:
# Run Apriori with your transactions
min_support = 0.1  # 10% minimum support
min_confidence = 0.7  # 70% minimum confidence

frequent_itemsets, association_rules = apriori2(transactions_clean, min_support, min_confidence)

Apriori
Total transactions: 4920
Minimum support: 10.0% (≥492.0)
Minimum confidence: 70.0%
Found 19 frequent 1 itemsets
Generating 2 itemsets
Found 33 frequent 2-itemsets
Generating 3 itemsets
Found 19 frequent 3-itemsets
Generating 4 itemsets
Found 2 frequent 4-itemsets
Generating 5 itemsets
  1-itemsets: 19
  2-itemsets: 33
  3-itemsets: 19
  4-itemsets: 2

STEP 2: GENERATING ASSOCIATION RULES...
Generated 70 association rules

In [24]:
# Display only 2-itemsets or greater
print("🔍 ALL ITEMSETS:")
print("=" * 80)
print(f"{'2-Itemset':<50} {'Support Count':<15} {'Support %':<10}")
print("-" * 80)

total_transactions = len(transactions_clean)

# Only show itemsets > 2
two_itemsets = {itemset: count for itemset, count in frequent_itemsets.items() if len(itemset) >= 2}
two_itemsets_sorted = sorted(two_itemsets.items(), key=lambda x: x[1], reverse=True)

for itemset, support_count in two_itemsets_sorted:
    support_percentage = (support_count / total_transactions) * 100
    itemset_str = str(tuple(itemset))
    print(f"{itemset_str:<50} {support_count:<15} {support_percentage:.1f}%")

print(f"\nTotal itemsets found: {len(two_itemsets)}")

🔍 ALL ITEMSETS:
================================================================================
2-Itemset                                          Support Count   Support %
--------------------------------------------------------------------------------
('nausea', 'vomiting')                             978             19.9%
('vomiting', 'stomach_pain')                       978             19.9%
('fatigue', 'high_fever')                          978             19.9%
('loss_of_appetite', 'yellowing_of_eyes')          786             16.0%
('loss_of_appetite', 'fatigue')                    774             15.7%
('loss_of_appetite', 'vomiting')                   768             15.6%
('yellowish_skin', 'stomach_pain')                 762             15.5%
('fatigue', 'vomiting')                            762             15.5%
('loss_of_appetite', 'nausea')                     666             13.5%
('malaise', 'fatigue')                             666             13.5%
('fatigue', 'nausea')                              660             13.4%
('chills', 'high_fever')                           660             13.4%
('yellowing_of_eyes', 'yellowish_skin')            660             13.4%
('loss_of_appetite', 'yellowish_skin')             654             13.3%
('vomiting', 'high_fever')                         654             13.3%
('loss_of_appetite', 'stomach_pain')               654             13.3%
('yellowish_skin', 'vomiting')                     648             13.2%
('headache', 'vomiting')                           642             13.0%
('loss_of_appetite', 'yellowish_skin', 'yellowing_of_eyes') 630             12.8%
('yellowish_skin', 'vomiting', 'stomach_pain')     618             12.6%
('yellowing_of_eyes', 'stomach_pain')              564             11.5%
('fatigue', 'stomach_pain')                        558             11.3%
('yellowing_of_eyes', 'vomiting')                  558             11.3%
('headache', 'high_fever')                         552             11.2%
('nausea', 'stomach_pain')                         552             11.2%
('malaise', 'high_fever')                          552             11.2%
('yellowing_of_eyes', 'fatigue')                   552             11.2%
('fatigue', 'headache')                            552             11.2%
('chills', 'fatigue')                              552             11.2%
('nausea', 'headache')                             552             11.2%
('dark_urine', 'stomach_pain')                     546             11.1%
('yellowing_of_eyes', 'nausea')                    546             11.1%
('nausea', 'yellowish_skin')                       540             11.0%
('fatigue', 'yellowish_skin')                      540             11.0%
('yellowish_skin', 'dark_urine')                   540             11.0%
('loss_of_appetite', 'yellowing_of_eyes', 'stomach_pain') 540             11.0%
('loss_of_appetite', 'vomiting', 'yellowing_of_eyes') 540             11.0%
('yellowing_of_eyes', 'yellowish_skin', 'stomach_pain') 534             10.9%
('yellowing_of_eyes', 'fatigue', 'loss_of_appetite') 534             10.9%
('chills', 'fatigue', 'high_fever')                528             10.7%
('loss_of_appetite', 'nausea', 'vomiting')         528             10.7%
('loss_of_appetite', 'yellowish_skin', 'stomach_pain') 522             10.6%
('nausea', 'vomiting', 'stomach_pain')             522             10.6%
('nausea', 'vomiting', 'headache')                 522             10.6%
('yellowing_of_eyes', 'nausea', 'loss_of_appetite') 522             10.6%
('fatigue', 'nausea', 'vomiting')                  522             10.6%
('fatigue', 'vomiting', 'high_fever')              522             10.6%
('malaise', 'fatigue', 'high_fever')               522             10.6%
('yellowish_skin', 'dark_urine', 'stomach_pain')   516             10.5%
('nausea', 'loss_of_appetite', 'yellowish_skin')   516             10.5%
('loss_of_appetite', 'vomiting', 'stomach_pain')   516             10.5%
('yellowing_of_eyes', 'nausea', 'yellowish_skin')  516             10.5%
('loss_of_appetite', 'yellowing_of_eyes', 'yellowish_skin', 'stomach_pain') 510             10.4%
('loss_of_appetite', 'nausea', 'yellowing_of_eyes', 'yellowish_skin') 492             10.0%

Total itemsets found: 54

In [23]:
# Analyze which diseases contain ALL itemsets (2-itemsets and larger)
print("DISEASES CONTAINING APRIORI ITEMSETS (2+ items)")
print("=" * 80)

# Define the disease column name for your dataset
disease_col = 'Disease'

# Get all itemsets with 2 or more items
multi_itemsets = {itemset: count for itemset, count in frequent_itemsets.items() if len(itemset) >= 2}
multi_itemsets_sorted = sorted(multi_itemsets.items(), key=lambda x: x[1], reverse=True)

# Precompute disease-symptom mappings for faster lookup
print("\nPrecomputing disease-symptom mappings...")
disease_symptoms = {}

for disease in df_clean[disease_col].unique():
    disease_data = df_clean[df_clean[disease_col] == disease]
    # Get all unique symptoms for this disease across all patients
    all_symptoms = set()
    for idx, patient in disease_data.iterrows():
        for col in [f'Symptom_{i}' for i in range(1, 18)]:
            if pd.notna(patient[col]) and patient[col] != '':
                all_symptoms.add(patient[col])
    disease_symptoms[disease] = all_symptoms

print("Disease-symptom mappings computed!")

itemset_to_diseases = {}
processed = 0

print(f"\nAnalyzing itemsets...")
for itemset, support_count in multi_itemsets_sorted:
    symptoms = set(itemset)  # Use set for faster operations
    processed += 1
    
    # Show progress
    if processed % 10 == 0:
        print(f"  Processed {processed}/{len(multi_itemsets_sorted)} itemsets...")
    
    # Find diseases that have ALL symptoms in this itemset
    matching_diseases = []
    
    for disease, disease_symptom_set in disease_symptoms.items():
        # Check if disease has ALL symptoms from the itemset
        if symptoms.issubset(disease_symptom_set):
            matching_diseases.append(disease)
    
    itemset_to_diseases[itemset] = {
        'diseases': matching_diseases,
        'support_count': support_count,
        'support_pct': (support_count / total_transactions) * 100
    }

print("Analysis complete!")

# Display ALL results organized by itemset size
print(f"\nCOMPLETE RESULTS - ALL ITEMSETS (2+ SYMPTOMS):")
print("=" * 70)

# Get all sizes present and sort them
all_sizes_present = sorted(set(len(itemset) for itemset in itemset_to_diseases.keys()))
print(f"Itemset sizes found: {all_sizes_present}")

for size in all_sizes_present:
    size_itemsets = [(itemset, data) for itemset, data in itemset_to_diseases.items() 
                     if len(itemset) == size]
    
    print(f"\n{'='*60}")
    print(f"{size}-SYMPTOM COMBINATIONS ({len(size_itemsets)} patterns)")
    print(f"{'='*60}")
    
    itemsets_with_diseases = 0
    
    for itemset, data in sorted(size_itemsets, key=lambda x: x[1]['support_count'], reverse=True):
        diseases_list = data['diseases']
        print(f"\n🔹 {tuple(itemset)}")
        print(f"   Support: {data['support_count']} patients ({data['support_pct']:.1f}%)")
        if diseases_list:
            itemsets_with_diseases += 1
            print(f"Associated Diseases: {', '.join(sorted(diseases_list))}")
        else:
            print(f"No disease contains all these symptoms together")
    
    print(f"\nSummary: {itemsets_with_diseases}/{len(size_itemsets)} {size}-item patterns have disease associations")

# Summary statistics
print(f"\n{'='*50}")
print(f"OVERALL SUMMARY")
print(f"{'='*50}")
total_itemsets_with_diseases = sum(1 for data in itemset_to_diseases.values() if data['diseases'])
print(f"Total itemsets analyzed: {len(multi_itemsets)}")
print(f"Itemsets with disease associations: {total_itemsets_with_diseases} ({total_itemsets_with_diseases/len(multi_itemsets)*100:.1f}%)")

# Find most common diseases across itemsets
disease_frequency = {}
for data in itemset_to_diseases.values():
    for disease in data['diseases']:
        disease_frequency[disease] = disease_frequency.get(disease, 0) + 1

if disease_frequency:
    print(f"\nTOP DISEASES BY ITEMSET ASSOCIATIONS:")
    for disease, freq in sorted(disease_frequency.items(), key=lambda x: x[1], reverse=True)[:15]:
        print(f"  {disease}: {freq} itemsets")

# Show key highlights
print(f"\n{'='*50}")
print(f"KEY HIGHLIGHTS")
print(f"{'='*50}")

# Top 3 itemsets by support
print(f"\nTOP 3 MOST FREQUENT SYMPTOM COMBINATIONS:")
top_support = sorted(itemset_to_diseases.items(), key=lambda x: x[1]['support_count'], reverse=True)[:3]
for i, (itemset, data) in enumerate(top_support, 1):
    print(f"  {i}. {tuple(itemset)} - {data['support_count']} patients ({data['support_pct']:.1f}%)")
    print(f"     Diseases: {', '.join(data['diseases'])}")

# Largest itemsets
largest_itemsets = sorted([(itemset, data) for itemset, data in itemset_to_diseases.items()], 
                         key=lambda x: len(x[0]), reverse=True)[:3]

DISEASES CONTAINING APRIORI ITEMSETS (2+ items)
================================================================================

Precomputing disease-symptom mappings...
Disease-symptom mappings computed!

Analyzing itemsets...
  Processed 10/54 itemsets...
  Processed 20/54 itemsets...
  Processed 30/54 itemsets...
  Processed 40/54 itemsets...
  Processed 50/54 itemsets...
Analysis complete!

COMPLETE RESULTS - ALL ITEMSETS (2+ SYMPTOMS):
======================================================================
Itemset sizes found: [2, 3, 4]

============================================================
2-SYMPTOM COMBINATIONS (33 patterns)
============================================================

🔹 ('nausea', 'vomiting')
   Support: 978 patients (19.9%)
Associated Diseases: (vertigo) Paroymsal  Positional Vertigo, Chronic cholestasis, Dengue, Hepatitis D, Hepatitis E, Hypoglycemia, Malaria, Typhoid, hepatitis A

🔹 ('vomiting', 'stomach_pain')
   Support: 978 patients (19.9%)
Associated Diseases: Alcoholic hepatitis, Chronic cholestasis, GERD, Hepatitis D, Hepatitis E, Jaundice, Peptic ulcer diseae, Typhoid, hepatitis A

🔹 ('fatigue', 'high_fever')
   Support: 978 patients (19.9%)
Associated Diseases: Bronchial Asthma, Chicken pox, Common Cold, Dengue, Hepatitis E, Jaundice, Pneumonia, Tuberculosis, Typhoid

🔹 ('loss_of_appetite', 'yellowing_of_eyes')
   Support: 786 patients (16.0%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, Tuberculosis, hepatitis A

🔹 ('loss_of_appetite', 'fatigue')
   Support: 774 patients (15.7%)
Associated Diseases: Chicken pox, Dengue, Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, Tuberculosis

🔹 ('loss_of_appetite', 'vomiting')
   Support: 768 patients (15.6%)
Associated Diseases: Chronic cholestasis, Dengue, Hepatitis D, Hepatitis E, Peptic ulcer diseae, Tuberculosis, hepatitis A

🔹 ('yellowish_skin', 'stomach_pain')
   Support: 762 patients (15.5%)
Associated Diseases: Alcoholic hepatitis, Chronic cholestasis, Hepatitis B, Hepatitis D, Hepatitis E, Jaundice, hepatitis A

🔹 ('fatigue', 'vomiting')
   Support: 762 patients (15.5%)
Associated Diseases: Dengue, Hepatitis D, Hepatitis E, Hypoglycemia, Jaundice, Tuberculosis, Typhoid

🔹 ('loss_of_appetite', 'nausea')
   Support: 666 patients (13.5%)
Associated Diseases: Chronic cholestasis, Dengue, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('malaise', 'fatigue')
   Support: 666 patients (13.5%)
Associated Diseases: Chicken pox, Common Cold, Dengue, Hepatitis B, Pneumonia, Tuberculosis

🔹 ('fatigue', 'nausea')
   Support: 660 patients (13.4%)
Associated Diseases: Dengue, Hepatitis C, Hepatitis D, Hepatitis E, Hypoglycemia, Typhoid

🔹 ('chills', 'high_fever')
   Support: 660 patients (13.4%)
Associated Diseases: Common Cold, Dengue, Malaria, Pneumonia, Tuberculosis, Typhoid

🔹 ('yellowing_of_eyes', 'yellowish_skin')
   Support: 660 patients (13.4%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('loss_of_appetite', 'yellowish_skin')
   Support: 654 patients (13.3%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('vomiting', 'high_fever')
   Support: 654 patients (13.3%)
Associated Diseases: Dengue, Hepatitis E, Jaundice, Malaria, Tuberculosis, Typhoid

🔹 ('loss_of_appetite', 'stomach_pain')
   Support: 654 patients (13.3%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis D, Hepatitis E, Peptic ulcer diseae, hepatitis A

🔹 ('yellowish_skin', 'vomiting')
   Support: 648 patients (13.2%)
Associated Diseases: Alcoholic hepatitis, Chronic cholestasis, Hepatitis D, Hepatitis E, Jaundice, hepatitis A

🔹 ('headache', 'vomiting')
   Support: 642 patients (13.0%)
Associated Diseases: (vertigo) Paroymsal  Positional Vertigo, Dengue, Hypoglycemia, Malaria, Paralysis (brain hemorrhage), Typhoid

🔹 ('yellowing_of_eyes', 'stomach_pain')
   Support: 564 patients (11.5%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('fatigue', 'stomach_pain')
   Support: 558 patients (11.3%)
Associated Diseases: Hepatitis B, Hepatitis D, Hepatitis E, Jaundice, Typhoid

🔹 ('yellowing_of_eyes', 'vomiting')
   Support: 558 patients (11.3%)
Associated Diseases: Chronic cholestasis, Hepatitis D, Hepatitis E, Tuberculosis, hepatitis A

🔹 ('headache', 'high_fever')
   Support: 552 patients (11.2%)
Associated Diseases: Chicken pox, Common Cold, Dengue, Malaria, Typhoid

🔹 ('nausea', 'stomach_pain')
   Support: 552 patients (11.2%)
Associated Diseases: Chronic cholestasis, Hepatitis D, Hepatitis E, Typhoid, hepatitis A

🔹 ('malaise', 'high_fever')
   Support: 552 patients (11.2%)
Associated Diseases: Chicken pox, Common Cold, Dengue, Pneumonia, Tuberculosis

🔹 ('yellowing_of_eyes', 'fatigue')
   Support: 552 patients (11.2%)
Associated Diseases: Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, Tuberculosis

🔹 ('fatigue', 'headache')
   Support: 552 patients (11.2%)
Associated Diseases: Chicken pox, Common Cold, Dengue, Hypoglycemia, Typhoid

🔹 ('chills', 'fatigue')
   Support: 552 patients (11.2%)
Associated Diseases: Common Cold, Dengue, Pneumonia, Tuberculosis, Typhoid

🔹 ('nausea', 'headache')
   Support: 552 patients (11.2%)
Associated Diseases: (vertigo) Paroymsal  Positional Vertigo, Dengue, Hypoglycemia, Malaria, Typhoid

🔹 ('dark_urine', 'stomach_pain')
   Support: 546 patients (11.1%)
Associated Diseases: Hepatitis B, Hepatitis D, Hepatitis E, Jaundice, hepatitis A

🔹 ('yellowing_of_eyes', 'nausea')
   Support: 546 patients (11.1%)
Associated Diseases: Chronic cholestasis, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('nausea', 'yellowish_skin')
   Support: 540 patients (11.0%)
Associated Diseases: Chronic cholestasis, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('fatigue', 'yellowish_skin')
   Support: 540 patients (11.0%)
Associated Diseases: Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, Jaundice

🔹 ('yellowish_skin', 'dark_urine')
   Support: 540 patients (11.0%)
Associated Diseases: Hepatitis B, Hepatitis D, Hepatitis E, Jaundice, hepatitis A

Summary: 33/33 2-item patterns have disease associations

============================================================
3-SYMPTOM COMBINATIONS (19 patterns)
============================================================

🔹 ('loss_of_appetite', 'yellowish_skin', 'yellowing_of_eyes')
   Support: 630 patients (12.8%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('yellowish_skin', 'vomiting', 'stomach_pain')
   Support: 618 patients (12.6%)
Associated Diseases: Alcoholic hepatitis, Chronic cholestasis, Hepatitis D, Hepatitis E, Jaundice, hepatitis A

🔹 ('loss_of_appetite', 'yellowing_of_eyes', 'stomach_pain')
   Support: 540 patients (11.0%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('loss_of_appetite', 'vomiting', 'yellowing_of_eyes')
   Support: 540 patients (11.0%)
Associated Diseases: Chronic cholestasis, Hepatitis D, Hepatitis E, Tuberculosis, hepatitis A

🔹 ('yellowing_of_eyes', 'yellowish_skin', 'stomach_pain')
   Support: 534 patients (10.9%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('yellowing_of_eyes', 'fatigue', 'loss_of_appetite')
   Support: 534 patients (10.9%)
Associated Diseases: Hepatitis B, Hepatitis C, Hepatitis D, Hepatitis E, Tuberculosis

🔹 ('chills', 'fatigue', 'high_fever')
   Support: 528 patients (10.7%)
Associated Diseases: Common Cold, Dengue, Pneumonia, Tuberculosis, Typhoid

🔹 ('loss_of_appetite', 'nausea', 'vomiting')
   Support: 528 patients (10.7%)
Associated Diseases: Chronic cholestasis, Dengue, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('loss_of_appetite', 'yellowish_skin', 'stomach_pain')
   Support: 522 patients (10.6%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('nausea', 'vomiting', 'stomach_pain')
   Support: 522 patients (10.6%)
Associated Diseases: Chronic cholestasis, Hepatitis D, Hepatitis E, Typhoid, hepatitis A

🔹 ('nausea', 'vomiting', 'headache')
   Support: 522 patients (10.6%)
Associated Diseases: (vertigo) Paroymsal  Positional Vertigo, Dengue, Hypoglycemia, Malaria, Typhoid

🔹 ('yellowing_of_eyes', 'nausea', 'loss_of_appetite')
   Support: 522 patients (10.6%)
Associated Diseases: Chronic cholestasis, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('fatigue', 'nausea', 'vomiting')
   Support: 522 patients (10.6%)
Associated Diseases: Dengue, Hepatitis D, Hepatitis E, Hypoglycemia, Typhoid

🔹 ('fatigue', 'vomiting', 'high_fever')
   Support: 522 patients (10.6%)
Associated Diseases: Dengue, Hepatitis E, Jaundice, Tuberculosis, Typhoid

🔹 ('malaise', 'fatigue', 'high_fever')
   Support: 522 patients (10.6%)
Associated Diseases: Chicken pox, Common Cold, Dengue, Pneumonia, Tuberculosis

🔹 ('yellowish_skin', 'dark_urine', 'stomach_pain')
   Support: 516 patients (10.5%)
Associated Diseases: Hepatitis B, Hepatitis D, Hepatitis E, Jaundice, hepatitis A

🔹 ('nausea', 'loss_of_appetite', 'yellowish_skin')
   Support: 516 patients (10.5%)
Associated Diseases: Chronic cholestasis, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('loss_of_appetite', 'vomiting', 'stomach_pain')
   Support: 516 patients (10.5%)
Associated Diseases: Chronic cholestasis, Hepatitis D, Hepatitis E, Peptic ulcer diseae, hepatitis A

🔹 ('yellowing_of_eyes', 'nausea', 'yellowish_skin')
   Support: 516 patients (10.5%)
Associated Diseases: Chronic cholestasis, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

Summary: 19/19 3-item patterns have disease associations

============================================================
4-SYMPTOM COMBINATIONS (2 patterns)
============================================================

🔹 ('loss_of_appetite', 'yellowing_of_eyes', 'yellowish_skin', 'stomach_pain')
   Support: 510 patients (10.4%)
Associated Diseases: Chronic cholestasis, Hepatitis B, Hepatitis D, Hepatitis E, hepatitis A

🔹 ('loss_of_appetite', 'nausea', 'yellowing_of_eyes', 'yellowish_skin')
   Support: 492 patients (10.0%)
Associated Diseases: Chronic cholestasis, Hepatitis C, Hepatitis D, Hepatitis E, hepatitis A

Summary: 2/2 4-item patterns have disease associations

==================================================
OVERALL SUMMARY
==================================================
Total itemsets analyzed: 54
Itemsets with disease associations: 54 (100.0%)

TOP DISEASES BY ITEMSET ASSOCIATIONS:
  Hepatitis E: 43 itemsets
  Hepatitis D: 40 itemsets
  hepatitis A: 32 itemsets
  Chronic cholestasis: 29 itemsets
  Dengue: 22 itemsets
  Hepatitis B: 20 itemsets
  Typhoid: 19 itemsets
  Tuberculosis: 17 itemsets
  Hepatitis C: 16 itemsets
  Jaundice: 13 itemsets
  Common Cold: 9 itemsets
  Hypoglycemia: 8 itemsets
  Malaria: 7 itemsets
  Chicken pox: 7 itemsets
  Pneumonia: 7 itemsets

==================================================
KEY HIGHLIGHTS
==================================================

TOP 3 MOST FREQUENT SYMPTOM COMBINATIONS:
  1. ('nausea', 'vomiting') - 978 patients (19.9%)
     Diseases: Chronic cholestasis, Malaria, Dengue, Typhoid, hepatitis A, Hepatitis D, Hepatitis E, Hypoglycemia, (vertigo) Paroymsal  Positional Vertigo
  2. ('vomiting', 'stomach_pain') - 978 patients (19.9%)
     Diseases: GERD, Chronic cholestasis, Peptic ulcer diseae, Jaundice, Typhoid, hepatitis A, Hepatitis D, Hepatitis E, Alcoholic hepatitis
  3. ('fatigue', 'high_fever') - 978 patients (19.9%)
     Diseases: Bronchial Asthma, Jaundice, Chicken pox, Dengue, Typhoid, Hepatitis E, Tuberculosis, Common Cold, Pneumonia